#+hugo_base_dir: ../
#+hugo_section: /post/
#+options: author:nil
#+options: ^:nil
[../static/img/messi-2014.jpg]]

* ✔ DONE 研究生招生                             :education:@教育:
CLOSED: [2014-03-23 Sun 23:31]
:PROPERTIES:
:EXPORT_FILE_NAME: grad-zhaoseng
:END:
又要到每年一度的研究生复试的时候了。在我们这样的学校，复试其实不是在选拔更优秀的学生，而大多是在调剂考别的学校分数不够或挑剩下的。因此，绝大多数考生对物理和化学的兴趣极低，只是为了读研究生而读，或者不想面对复杂的社会，不敢去找工作。

每当这时，我都心情极其复杂，对于测不准原理都无法正确描述、表象是什么意思都一片茫然的学生来说，这个物理的硕士学位该如何读下去？我根本不相信在研究生阶段他/她可以奋发用功，既可以把基础补上来，还能够攻克更艰深的学术问题。因为，从他们的眼神里我没有看到任何对知识的渴望，对科学的向往，对真理的追求……

作为一个自由主义分子，按照我的本性，我应该劝他/她不要读这个物理学位，而去找寻自己喜爱的事情。即使今年找不到，来年，或者两三年之后一定可以圆梦。

以往，我就是这样做的。我很自由自在，学生也很开心。结果，自然也是皆大欢喜的。可是现在，我却不能这样随心所欲---因为我要维护这个硕士点的存在。如果我这样劝说学生，就会招不够学生，明年招生名额就会减少，慢慢硕士点就会被取消。所以，每个点的负责老师这几天都在想方设法地动用各种关系，巧舌如簧，“坑蒙拐骗”，只要能把学生诓进自己的圈子。各位老师，也在明争暗斗，以期能多几个劳力。每次看到这样的场景，我都会想起车站里拉客的导游，或者住宿，或者拉车。无论条件如何，只要上了他们的车，你就无可奈何，他也大功告成。

我什么时候变成这样的拉客了？我崇尚的自由选择、随心所欲又到哪里去了？就因为我在这样的体制下，就因为我要维护既得利益吗？

这不是我的本性。实际上，我一点也不热衷于指导学生。在我看来，每个人都是平等的，包括老师和学生。大家在一起，是因为对某个问题感兴趣，共同来解决而已。在这个过程中，你愿意学，我就愿意讲；你喜欢听，我就乐于分享。如果我也不懂，就和你一起学习。如果你先明白，我安于做你的学生。今后，你展翅高飞，我在这里欢喜祝福。

所以，我的学生很少。我不羡慕，更耻于与靠学生赢利的人为伍。

* ✔ DONE 素质教育                              :education:@教育:
CLOSED: [2014-03-09 Sun 23:32]
:PROPERTIES:
:EXPORT_FILE_NAME: suzhi-jiaoyu
:END:

什么是素质教育？素质教育的目的是什么？答案其实非常简单。

1. 培养健全的人格
2. 培养学习的能力

说的再通俗一点，就是培养适应社会、适应发展的能力。这个能力应该是每个大学生的基本能力，拥有这个能力的人才能叫大学生或者是本科生。

21 世纪的今天，专业对口应该是一个世界难题了吧？我们教科书的内容能跟上这个社会的发展吗？如何让我们通过学两本教材就能干好某个工作？比世界难题可能还要难。有些教育工作者思考的出发点是落后的，让我想起了那个广告，“学技术，去蓝翔。”

蓝翔的技校生的标准是记住“修车的过程”就可以了，大学的理工科学生必须还要思考、学习“车为什么这么修”，更要去研究“怎么修更好”。这种思考的能力和欲望就是素质教育培养的内容，这也是技工和工程师的本质区别，更是技校和大学的本质区别。说的再简单一点就是四个字---君子不器。

大学出来的学生迷茫、迷惑是正常的，懂得思考的人才会有迷茫，如果短短四年就让你把理想、把社会这些需要思考的东西都想明白，那才是奇怪的。不迷茫的人往往不去想，上班挣钱混日子。没有理想的人多了才是可怕的。

对综合素质的培养，其出发点是毋庸置疑的，适应发展、适应社会，君子不器。中国高校在培养综合素质的方面和西方还是有差距的，强调的标准倒是不少，但扯淡的成分居多，而且教育内容落后。我觉得中国高校可以参考美国一些高校的通识教育课程，学习他们的课程设置，提高真正的素质能力。

* ✔ DONE 《漫谈二流大学》                        :education:@教育:
CLOSED: [2014-02-08 Sat 15:06]
:PROPERTIES:
:EXPORT_FILE_NAME: erliu-daxue
:END:

我一直觉得博客要自己写的才好，老转他人的文章不舒服。但今天看到李志文先生的这篇文章，很有感触，基本同意他的观点。链接在此，时而温习之。

[[http://www.rocidea.com/one?id=26164][漫谈二流大学]]

如果打不开链接，我将原文复制如下：

-----------------------------------------------------------

#+INCLUDE: "~/Documents/RDS/NOTES/Org/Roam/reference/漫谈二流大学.org"
